### ISSUE TITLE
Got an error when using 'random_forest_regressor' estimator 

### ISSUE THREAD

**Issue by Guo-lingyun** [scverse/pertpy#634]
### Report

Since my data had four timepoints-treated conditions, I tried to use 'random_forest_regressor ' estimator which was described for continuous data in the tutorial:
`augur = pt.tl.Augur("random_forest_regressor")`
`treat_augur=augur.load(treat,label_col='group',cell_type_col='celltype')`
`treat_augur, treat_augur_results = augur.predict(treat_augur, random_state=None, n_threads=4)`
However, I got an error in the predicting step:
`AttributeError: RandomForestRegressor has none of the following attributes: predict_proba.`

**Comment by Zethson** [comment]
Could you please tell me which versions you used? The issue template is there for a reason. I can help best if you provide all information.

**Comment by Zethson** [comment]
I assume that your scikit-learn version is old.

**Comment by Zethson** [comment]
Please report back with more information if he error persists.
