### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by Zethson** [scverse/pertpy#643]
### Description of feature

- [x] Check whether tests and use-cases run with Python 3.12. It might be annoying to rerun all tutorials so let's primarily keep it to the tests + maybe the paper use-cases?
- [x] Replace Python 3.11 in the CI with 3.12
- [x] Add it in the pyproject.toml

**Comment by Lilly-May** [comment]
Sounds good! I'm on it.

**Comment by Lilly-May** [comment]
ToDos 2 and 3 are addressed in PR #644. I'll verify that the use cases work with Python 3.12 while converting the use-case notebooks into tutorials for the docs (see #642), so I'll keep this issue open for now.

**Comment by Lilly-May** [comment]
I ran the paper use-cases with Python 3.12 and created https://github.com/scverse/pertpy-tutorials/pull/48. Hence, I'll close this issue.
