### ISSUE TITLE
Import Error: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping'

### ISSUE THREAD

**Issue by LJZYaaa** [scverse/pertpy#650]
### Report

Hi, i create a conda env which python=3.11,  and  then install the pertpy using "pip intall pertpy", however after successfully installed, when i try to import pertpy, i report as below:
![image](https://github.com/user-attachments/assets/36a4d7fd-1fa9-41b4-9e2c-2d298de3ef19)

**Comment by LJZYaaa** [comment]
Could you please give me some advice?

**Comment by Zethson** [comment]
Dear @LJZYaaa that's because of the latest anndata release which broke mudata. Could you please downgrade your anndata version?

`pip install -U anndata=0.10.8`

These issues will be fixed within scverse in the coming hours.

**Comment by Zethson** [comment]
Please report back if my advice above did not help you solve the issue, please!

**Comment by LJZYaaa** [comment]
Thanks for your quickly reply! I have tried the solution your kindly offered, i don't report Error right now!!! @Zethson

**Comment by wangjiawen2013** [comment]
Is it fixed ? anndata 0.11.0 still has this issue.

**Comment by wangjiawen2013** [comment]
I updated to latest mudata and it worked now.
