### ISSUE TITLE
Pertpy Plot Coda Module Gone?

### ISSUE THREAD

**Issue by alexjimenez99** [scverse/pertpy#656]
### Description of feature

I was following along on a tutorial (https://www.sc-best-practices.org/conditions/compositional.html ) for analyzing cell composition with sccoda and it appears the pertpy.plot.coda.boxplots method is not present. In fact, the whole __init__ file is empty for the pertpy.plot module. I was curious if this a purposeful removement of plotting functions or if this was added accidentally as a part of separate code commit.

**Comment by alexjimenez99** [comment]
No worries @Zethson. Thanks for the quick response.

**Comment by Zethson** [comment]
I updated best practices.
