### ISSUE TITLE
AttributeError: module 'pertpy.plot' has no attribute 'ag'

### ISSUE THREAD

**Issue by sunjiahe-hub** [scverse/pertpy#661]
### Report

I have updated the pertpy package with pip to version 0.9.4, but it still says "AttributeError: module 'pertpy.plot' has no attribute 'ag'". How should I fix this bug?

>>> lollipop = pt.pl.ag.lollipop(v_results)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 1
----> 1 lollipop = pt.pl.ag.lollipop(v_results)

AttributeError: module 'pertpy.plot' has no attribute 'ag'

pertpy Version:

import pertpy
>>>print(pertpy.__version__)
0.9.4

**Comment by Zethson** [comment]
Hi,

sorry, you are looking at old syntax. The plot is now a function of the `Augur()` object. I assume you got this from best practices. I'll update it.

**Comment by Zethson** [comment]
Actually, this is not used in best practices anymore... where did you still see this syntax?
