### ISSUE TITLE
Incorporating memento for more efficient and diverse differential analyses

### ISSUE THREAD

**Issue by SNOL2** [scverse/pertpy#676]
### Description of feature

Hi, have you considered adding memento(https://www.cell.com/cell/fulltext/S0092-8674(24)01144-9#) into pertpy framework, which enable faster and diverse differential analyses. In addition, it produced accurate estimates of false positives while maintaining high statistical power compared with pseudobulk methods or t-test.
Thanks in advance!

**Comment by Zethson** [comment]
Dear @SNOL2,

thank you for the feature request! A few thoughts:
1. There already exists a Python implementation. It might not be good, but we'd not like to compete with them. Only if they're interested in archiving theirs and use our DE base classes, I'd consider implementing it.
2. I want to see more independent benchmarks to learn how good the method really is.
3. We currently have a looooot of other issues and priorities. We will not have the time for this and therefore would be dependent on someone making a PR for it.

Let me know if you're interested in that and potentially coordinating a joint implementation with the original authors. If not, I currently deem this out of scope.
